### ISSUE TITLE
produces empty csv files 

### ISSUE THREAD

**Issue by crimsdings** [noghte/rottentomatoes#1]
No matter what RT url i run it with, it produces an "emtpy" csv

e.g:
cat joker_2019-critics-20191012-101030.csv
Title,Title_link,Thumbnail,col-sm-13,the_review,small,small1,review_date

this part does not work .. will look into it

`    for data in zip(titles, title_links, tumbnails, colsm13, the_review, small, small1, review_date):
        row = {}
        row['Title'] = data[0]
        row['Title_link'] = data[1]
        row['Thumbnail'] = data[2]
        row['col-sm-13'] = data[3]
        row['the_review'] = data[4]
        row['small'] = data[5]
        row['small1'] = data[6]
        row['review_date'] = data[7]
        items.append(row)
`

**Comment by noghte** [comment]
Thanks for reporting the issue. It seems rottentomatoes.com had some subtle changes in the review pages. I have updated the code.
